spring:
  main:
    log-startup-info: false
    banner-mode: 'off'
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
      fetch-registry: true
      register-with-eureka: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    org.springframework.cloud.netflix.eureka: OFF
    
    org.springframework.cloud.config: OFF
    org.springframework.boot.context.config: OFF
    
    org.springframework.boot.actuate.health: OFF
    com.netflix.discovery.shared.transport: OFF
    
    org.apache.http: OFF
    org.springframework.web.client.RestTemplate: OFF
    org:
      springframework:
        web: error
        security:
          nodeValue: error
          web:
            FilterChainProxy: error
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: error
        SQL: error

server:
  port: '8082'