spring:
  application:
    name: task-tracker-email-sender
  main:
    log-startup-info: false
    banner-mode: 'off'
  kafka:
    listener:
      ack-mode: record
    consumer:
      group-id: kafka-core-consumer-group
      auto-offset-reset: earliest
    properties:
      metrics:
        num:
          samples: 4
  mail:
    host: smtp.gmail.com
    port: 587
    username: loucterso@gmail.com
    password: 123123
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org:
      springframework:
        web: error
        security:
          nodeValue: error
          web:
            FilterChainProxy: error
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: error
        SQL: error