
services:
  postgresdb:
    image: 'postgres'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: backend
    volumes:
      - data:/var/lib/postgresql/data

  task-tracker-backend:
    build:
      context: ./task-tracker-backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgresdb

volumes:
  data: