hibernate:
  format_sql: 'false'
  show_sql: 'false'

spring:
  application:
    name: task-tracker-backend
  main:
    log-startup-info: false
    banner-mode: 'off'
  jpa:
    properties:
      hibernate:
        format-sql: 'false'
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/backend
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    org:
      springframework:
        web: error
        security:
          nodeValue: error
          web:
            FilterChainProxy: error
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: error
        SQL: error

server:
  servlet:
    context-path: /api/v1
  port: '8080'
