hibernate:
  format_sql: 'false'
  show_sql: 'false'

spring:
  application:
    name: task-tracker-backend
  main:
    banner-mode: 'off'
    log-startup-info: false
  jpa:
    properties:
      hibernate:
        format-sql: 'false'
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/backend
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.Serializer<io.github.LoucterSo.task_tracker_backend.form.email.EmailDto>

logging:
  level:
    org:
      springframework:
        web: error
        security:
          nodeValue: error
          web:
            FilterChainProxy: error
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: error
        SQL: error

jwt:
  refresh:
    lifetime: '2592000000'
  secret: 5u8ADYq3thVmYq3t6w9zCEHxADGYq3thVmYq3t6w9zCEHxDGGKbPeSVmYq3thVmYq3t6Yq3thVmYq3t6w9zCEHxADGPeShVmVmYq3tYq3t6w9zCDGKbPeSw9zCEHxAD3t6w9zCEHGmYVmYq3tq3t6w9zCE
  access:
    lifetime: '900000'

server:
  servlet:
    context-path: /api/v1
  port: '8080'

