spring:
  application:
    name: task-tracker-scheduler
  main:
    log-startup-info: false
    banner-mode: 'off'
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
      fetch-registry: true
      register-with-eureka: true

logging:
  level:
    org:
      springframework:
        web: error
        security:
          nodeValue: error
          web:
            FilterChainProxy: error
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: error
        SQL: error

server:
  port: '8082'
