server:
  port: 8761

spring:
  application:
    name: eureka-server
  main:
    log-startup-info: false
    banner-mode: 'off'

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false