spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LoucterSo/multi-user-task-scheduler.git
          search-paths: 'config/{profile}'
          clone-on-start: true
          force-pull: true
          default-label: main
server:
  port: 8888


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
      fetch-registry: true
      register-with-eureka: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    org.springframework.cloud.netflix.eureka: OFF

    org.springframework.cloud.config: OFF
    org.springframework.boot.context.config: OFF

    org.springframework.boot.actuate.health: OFF
    com.netflix.discovery.shared.transport: OFF

    org.apache.http: OFF
    org.springframework.web.client.RestTemplate: OFF